site_name: TPI_evoluto Docs
repo_url: https://github.com/aicreator76/TPI_evoluto
edit_uri: blob/main/docs/

theme:
  name: material




  features:
    - navigation.tabs
    - navigation.sections
@@ -18,3 +16,4 @@ nav:
  - API:
    - OpenAPI: openapi.md
    - "Schema (JSON)": openapi.json


