site_name: TPI_evoluto Docs
site_url: https://aicreator76.github.io/TPI_evoluto/
theme:
  name: material
plugins:
  - search
nav:
  - Home: index.md
  - Catalogo:
    - Overview: catalogo/index.md
    - Endpoint HTTP: http/catalogo_endpoints.md
