site_name: TPI_evoluto Docs
site_url: https://aicreator76.github.io/TPI_evoluto/
repo_url: https://github.com/aicreator76/TPI_evoluto
edit_uri: edit/main/docs/

theme:
  name: material

plugins:
  - search
  - swagger-ui-tag

nav:
  - Home: index.md
  - API: openapi.md

markdown_extensions:
  - admonition
  - tables
  - toc:
      permalink: true

